// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateAll(arg1) {
  return window['go']['main']['App']['GenerateAll'](arg1);
}

export function GeneratePreview() {
  return window['go']['main']['App']['GeneratePreview']();
}

export function GetColumns() {
  return window['go']['main']['App']['GetColumns']();
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetExcelPath() {
  return window['go']['main']['App']['GetExcelPath']();
}

export function GetFonts() {
  return window['go']['main']['App']['GetFonts']();
}

export function GetOutputDir() {
  return window['go']['main']['App']['GetOutputDir']();
}

export function GetPreviewRows(arg1) {
  return window['go']['main']['App']['GetPreviewRows'](arg1);
}

export function GetSampleText(arg1) {
  return window['go']['main']['App']['GetSampleText'](arg1);
}

export function GetTemplateBase64() {
  return window['go']['main']['App']['GetTemplateBase64']();
}

export function GetTemplatePath() {
  return window['go']['main']['App']['GetTemplatePath']();
}

export function LoadFields() {
  return window['go']['main']['App']['LoadFields']();
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['main']['App']['OpenDirectoryDialog'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFileDialog(arg1) {
  return window['go']['main']['App']['OpenFileDialog'](arg1);
}

export function SaveFields(arg1) {
  return window['go']['main']['App']['SaveFields'](arg1);
}

export function SelectExcel(arg1) {
  return window['go']['main']['App']['SelectExcel'](arg1);
}

export function SelectFont(arg1) {
  return window['go']['main']['App']['SelectFont'](arg1);
}

export function SelectTemplate(arg1) {
  return window['go']['main']['App']['SelectTemplate'](arg1);
}
