// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {frontend} from '../models';

export function GenerateAll(arg1:string):Promise<Record<string, any>>;

export function GeneratePreview():Promise<Record<string, any>>;

export function GetColumns():Promise<Array<string>>;

export function GetDataDir():Promise<string>;

export function GetExcelPath():Promise<string>;

export function GetFonts():Promise<Array<string>>;

export function GetOutputDir():Promise<string>;

export function GetPreviewRows(arg1:number):Promise<Array<any>>;

export function GetSampleText(arg1:string):Promise<string>;

export function GetTemplateBase64():Promise<string>;

export function GetTemplatePath():Promise<string>;

export function LoadFields():Promise<Array<config.Field>>;

export function OpenDirectoryDialog(arg1:frontend.OpenDialogOptions):Promise<string>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFileDialog(arg1:frontend.OpenDialogOptions):Promise<string>;

export function SaveFields(arg1:Array<config.Field>):Promise<void>;

export function SelectExcel(arg1:string):Promise<void>;

export function SelectFont(arg1:string):Promise<void>;

export function SelectTemplate(arg1:string):Promise<void>;
